/**
 * Alert Types
 *
 * [TASK-120] AI Alerts InboxBlock
 *
 * Types for pipeline alerts generated by AI analysis of deal state.
 */

/**
 * AlertType - Categories of pipeline alerts
 */
export const AlertType = {
  STAGE_OVERDUE: 'STAGE_OVERDUE',           // Deal stuck in stage too long
  DOCUMENT_PENDING: 'DOCUMENT_PENDING',     // Documents awaiting processing
  ACTION_REQUIRED: 'ACTION_REQUIRED',       // User action needed
  FOLLOW_UP_DUE: 'FOLLOW_UP_DUE',           // Scheduled follow-up due
} as const

export type AlertTypeValue = (typeof AlertType)[keyof typeof AlertType]

/**
 * AlertPriority - Urgency levels for alerts
 */
export const AlertPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const

export type AlertPriorityValue = (typeof AlertPriority)[keyof typeof AlertPriority]

/**
 * AlertStatus - Current state of an alert
 */
export const AlertStatus = {
  ACTIVE: 'ACTIVE',
  SNOOZED: 'SNOOZED',
  DISMISSED: 'DISMISSED',
} as const

export type AlertStatusValue = (typeof AlertStatus)[keyof typeof AlertStatus]

/**
 * DealAlert - Pipeline alert for a specific deal
 */
export interface DealAlert {
  id: string
  dealId: string
  dealName: string
  type: AlertTypeValue
  priority: AlertPriorityValue
  status: AlertStatusValue
  message: string
  metadata: {
    daysInStage?: number
    currentStage?: string
    pendingDocuments?: number
    followUpDate?: string
  }
  snoozeUntil: Date | null
  createdAt: Date
}

/**
 * AlertListResult - Paginated alert list response
 */
export interface AlertListResult {
  items: DealAlert[]
  pagination: {
    page: number
    pageSize: number
    total: number
    hasMore: boolean
  }
}
