/**
 * Seed script: Facts
 * Creates 50 verifiable facts with citations and confidence scores
 */

import { PrismaClient, Document, FactType } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedFacts(documents: Document[]) {
  console.log('💡 Seeding facts...');

  if (documents.length < 10) {
    throw new Error('Need at least 10 documents to seed facts');
  }

  // Filter only INDEXED documents for facts (exclude PROCESSING)
  const indexedDocs = documents.filter(d => d.status === 'INDEXED');

  const factsData = [
    // CloudSync Technologies facts (docs[0] - Company Overview, docs[1] - Financials)
    {
      documentId: indexedDocs[0].id,
      companyId: indexedDocs[0].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CloudSync Technologies',
      predicate: 'annual_recurring_revenue',
      object: '$12.5M ARR as of Q4 2024',
      confidence: 0.95,
      sourceText: 'CloudSync Technologies has achieved $12.5M in annual recurring revenue with 85 enterprise customers.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[0].id,
      companyId: indexedDocs[0].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CloudSync Technologies',
      predicate: 'customer_count',
      object: '85 enterprise customers',
      confidence: 0.95,
      sourceText: 'CloudSync Technologies has achieved $12.5M in annual recurring revenue with 85 enterprise customers.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[1].id,
      companyId: indexedDocs[1].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CloudSync Technologies',
      predicate: 'gross_margin',
      object: '78% gross margin',
      confidence: 0.92,
      sourceText: 'Financial statements show a consistent 78% gross margin with strong unit economics.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[0].id,
      companyId: indexedDocs[0].companyId,
      type: FactType.KEY_PERSON,
      subject: 'CloudSync Technologies',
      predicate: 'founder_ceo',
      object: 'Jane Mitchell, Founder & CEO',
      confidence: 0.98,
      sourceText: 'Founded in 2018 by Jane Mitchell (ex-Google Cloud, Stanford CS), CloudSync has grown to 85 employees.',
      extractedBy: 'claude-sonnet-4.5',
    },

    // DataVault Security facts (docs[2] - CIM, docs[3] - Contracts, docs[4] - IP)
    {
      documentId: indexedDocs[2].id,
      companyId: indexedDocs[2].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'DataVault Security',
      predicate: 'revenue_2024',
      object: '$18.3M revenue in 2024',
      confidence: 0.97,
      sourceText: 'DataVault generated $18.3M in revenue for fiscal year 2024, representing 65% YoY growth.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[2].id,
      companyId: indexedDocs[2].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'DataVault Security',
      predicate: 'growth_rate',
      object: '65% YoY revenue growth',
      confidence: 0.97,
      sourceText: 'DataVault generated $18.3M in revenue for fiscal year 2024, representing 65% YoY growth.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[3].id,
      companyId: indexedDocs[3].companyId,
      type: FactType.CUSTOMER,
      subject: 'DataVault Security',
      predicate: 'enterprise_customers',
      object: 'Fortune 500 customers including 3 major banks',
      confidence: 0.90,
      sourceText: 'Customer roster includes Fortune 500 companies with 3 major financial institutions as anchor clients.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[4].id,
      companyId: indexedDocs[4].companyId,
      type: FactType.PRODUCT,
      subject: 'DataVault Security',
      predicate: 'patents',
      object: '7 issued patents in data encryption',
      confidence: 0.99,
      sourceText: 'DataVault holds 7 issued US patents covering novel encryption methods and 4 pending applications.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[2].id,
      companyId: indexedDocs[2].companyId,
      type: FactType.RISK,
      subject: 'DataVault Security',
      predicate: 'customer_concentration',
      object: 'Top 3 customers represent 45% of revenue',
      confidence: 0.88,
      sourceText: 'Customer concentration risk exists with top 3 customers accounting for 45% of total revenue.',
      extractedBy: 'claude-sonnet-4.5',
    },

    // CustomerOS facts (docs[5-8])
    {
      documentId: indexedDocs[5].id,
      companyId: indexedDocs[5].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CustomerOS',
      predicate: 'revenue_2023',
      object: '$16.7M in audited 2023 revenue',
      confidence: 0.99,
      sourceText: 'Audited financial statements confirm $16.7M in total revenue for fiscal year 2023.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[6].id,
      companyId: indexedDocs[6].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CustomerOS',
      predicate: 'nrr',
      object: '125% net revenue retention',
      confidence: 0.93,
      sourceText: 'Net revenue retention of 125% demonstrates strong upsell and expansion motion within existing accounts.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[6].id,
      companyId: indexedDocs[6].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CustomerOS',
      predicate: 'ltv_cac',
      object: '5.2x LTV/CAC ratio',
      confidence: 0.91,
      sourceText: 'Customer economics show a healthy 5.2:1 lifetime value to customer acquisition cost ratio.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[7].id,
      companyId: indexedDocs[7].companyId,
      type: FactType.PRODUCT,
      subject: 'CustomerOS',
      predicate: 'tech_stack',
      object: 'React, Node.js, PostgreSQL, AWS infrastructure',
      confidence: 0.96,
      sourceText: 'Platform built on modern tech stack: React frontend, Node.js backend, PostgreSQL database, hosted on AWS.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[8].id,
      companyId: indexedDocs[8].companyId,
      type: FactType.KEY_PERSON,
      subject: 'CustomerOS',
      predicate: 'key_hires',
      object: '25% of employees have stock options vesting over 4 years',
      confidence: 0.94,
      sourceText: 'Employee agreements show 25% of workforce holds stock options with standard 4-year vesting schedules.',
      extractedBy: 'claude-sonnet-4.5',
    },

    // PaymentFlow facts (docs[9-13])
    {
      documentId: indexedDocs[9].id,
      companyId: indexedDocs[9].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'PaymentFlow',
      predicate: 'ebitda',
      object: '$8.2M adjusted EBITDA (23% margin)',
      confidence: 0.96,
      sourceText: 'Quality of earnings analysis confirms $8.2M in adjusted EBITDA representing a 23% margin.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[9].id,
      companyId: indexedDocs[9].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'PaymentFlow',
      predicate: 'recurring_revenue',
      object: '92% of revenue is recurring',
      confidence: 0.98,
      sourceText: 'Revenue quality is strong with 92% classified as recurring subscription and transaction-based fees.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[10].id,
      companyId: indexedDocs[10].companyId,
      type: FactType.CUSTOMER,
      subject: 'PaymentFlow',
      predicate: 'customer_base',
      object: '1,450 active business customers',
      confidence: 0.95,
      sourceText: 'Customer list shows 1,450 active businesses processing payments through the platform.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[10].id,
      companyId: indexedDocs[10].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'PaymentFlow',
      predicate: 'payment_volume',
      object: '$2.4B in annual payment volume',
      confidence: 0.97,
      sourceText: 'Platform processed $2.4B in total payment volume across all customers in the trailing twelve months.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[11].id,
      companyId: indexedDocs[11].companyId,
      type: FactType.RISK,
      subject: 'PaymentFlow',
      predicate: 'regulatory_compliance',
      object: 'PCI DSS Level 1 certified, SOC 2 Type II compliant',
      confidence: 0.99,
      sourceText: 'Regulatory compliance report confirms PCI DSS Level 1 certification and SOC 2 Type II compliance.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[12].id,
      companyId: indexedDocs[12].companyId,
      type: FactType.PRODUCT,
      subject: 'PaymentFlow',
      predicate: 'api_integrations',
      object: '50+ pre-built integrations with accounting and ERP systems',
      confidence: 0.92,
      sourceText: 'API documentation lists 50+ pre-built integrations with major accounting platforms (QuickBooks, Xero, NetSuite).',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[13].id,
      companyId: indexedDocs[13].companyId,
      type: FactType.RISK,
      subject: 'PaymentFlow',
      predicate: 'security_posture',
      object: 'No critical vulnerabilities in latest penetration test',
      confidence: 0.94,
      sourceText: 'Security audit report shows zero critical or high-severity vulnerabilities in latest penetration testing.',
      extractedBy: 'claude-sonnet-4.5',
    },

    // CloudDocs Platform facts (docs[14-16])
    {
      documentId: indexedDocs[14].id,
      companyId: indexedDocs[14].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CloudDocs Platform',
      predicate: 'purchase_price',
      object: '$175M proposed purchase price',
      confidence: 0.99,
      sourceText: 'Draft purchase agreement outlines a total consideration of $175M consisting of $140M cash and $35M earnout.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[14].id,
      companyId: indexedDocs[14].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CloudDocs Platform',
      predicate: 'earnout_structure',
      object: '$35M earnout tied to 2026 revenue targets',
      confidence: 0.97,
      sourceText: 'Earnout component of $35M contingent on achieving $40M in 2026 revenue with pro-rata adjustment.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[15].id,
      companyId: indexedDocs[15].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'CloudDocs Platform',
      predicate: 'valuation_multiple',
      object: '6.1x revenue multiple',
      confidence: 0.96,
      sourceText: 'Valuation report supports 6.1x trailing revenue multiple based on comparable SaaS transactions.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[16].id,
      companyId: indexedDocs[16].companyId,
      type: FactType.OPPORTUNITY,
      subject: 'CloudDocs Platform',
      predicate: 'growth_opportunity',
      object: 'Management projects 40% CAGR for next 3 years',
      confidence: 0.85,
      sourceText: 'Management presentation outlines 40% compound annual growth rate forecast driven by enterprise expansion.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[16].id,
      companyId: indexedDocs[16].companyId,
      type: FactType.PRODUCT,
      subject: 'CloudDocs Platform',
      predicate: 'product_roadmap',
      object: 'AI-powered document search launching Q3 2025',
      confidence: 0.90,
      sourceText: 'Product roadmap highlights AI-powered semantic document search as flagship feature for Q3 2025 release.',
      extractedBy: 'claude-sonnet-4.5',
    },

    // DevOps Central facts (docs[17-19])
    {
      documentId: indexedDocs[17].id,
      companyId: indexedDocs[17].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'DevOps Central',
      predicate: 'final_price',
      object: '$145M final purchase price',
      confidence: 0.99,
      sourceText: 'Final purchase agreement executed at $145M total consideration, all cash transaction.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[18].id,
      companyId: indexedDocs[18].companyId,
      type: FactType.OTHER,
      subject: 'DevOps Central',
      predicate: 'closing_conditions',
      object: 'All closing conditions satisfied as of June 28, 2025',
      confidence: 0.98,
      sourceText: 'Closing checklist confirms all representations, warranties, and closing conditions have been satisfied.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[19].id,
      companyId: indexedDocs[19].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'DevOps Central',
      predicate: 'wire_amount',
      object: '$145M wire transfer scheduled for June 30, 2025',
      confidence: 0.99,
      sourceText: 'Wire transfer instructions confirm $145M payment to seller accounts on June 30, 2025 closing date.',
      extractedBy: 'claude-sonnet-4.5',
    },

    // AnalyticsHub Pro facts (docs[20-22])
    {
      documentId: indexedDocs[20].id,
      companyId: indexedDocs[20].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'AnalyticsHub Pro',
      predicate: 'acquisition_price',
      object: '$98M acquisition completed May 2025',
      confidence: 0.99,
      sourceText: 'Executed purchase agreement confirms $98M all-cash acquisition closed on May 20, 2025.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[21].id,
      companyId: indexedDocs[21].companyId,
      type: FactType.OTHER,
      subject: 'AnalyticsHub Pro',
      predicate: 'closing_documents',
      object: 'Complete closing binder with 45 executed documents',
      confidence: 0.97,
      sourceText: 'Closing binder contains 45 fully executed transaction documents including agreements, schedules, and certificates.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[22].id,
      companyId: indexedDocs[22].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'AnalyticsHub Pro',
      predicate: 'final_revenue',
      object: '$14.8M trailing twelve month revenue at close',
      confidence: 0.98,
      sourceText: 'Final financial statements show $14.8M in trailing twelve month revenue as of closing date.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[22].id,
      companyId: indexedDocs[22].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'AnalyticsHub Pro',
      predicate: 'customer_metrics',
      object: '95 enterprise customers with $156K average contract value',
      confidence: 0.94,
      sourceText: 'Customer analysis shows 95 enterprise accounts with average annual contract value of $156K.',
      extractedBy: 'claude-sonnet-4.5',
    },

    // Additional facts from remaining documents
    {
      documentId: indexedDocs[23].id,
      companyId: indexedDocs[23].companyId,
      type: FactType.RISK,
      subject: 'LendingBridge',
      predicate: 'credit_risk',
      object: '2.3% default rate on loan portfolio',
      confidence: 0.92,
      sourceText: 'Risk assessment shows 2.3% historical default rate on small business loan portfolio, below industry average.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[23].id,
      companyId: indexedDocs[23].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'LendingBridge',
      predicate: 'loan_volume',
      object: '$425M in loans originated in 2024',
      confidence: 0.95,
      sourceText: 'Platform originated $425M in total loan volume across 1,200 small business borrowers in 2024.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[24].id,
      companyId: indexedDocs[24].companyId,
      type: FactType.RISK,
      subject: 'HealthTrack Systems',
      predicate: 'regulatory_compliance',
      object: 'HIPAA compliant with annual audits',
      confidence: 0.98,
      sourceText: 'HIPAA compliance audit confirms full adherence to privacy and security rules with no violations.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[24].id,
      companyId: indexedDocs[24].companyId,
      type: FactType.CUSTOMER,
      subject: 'HealthTrack Systems',
      predicate: 'healthcare_providers',
      object: '230 healthcare providers using platform',
      confidence: 0.96,
      sourceText: 'Customer base includes 230 healthcare provider organizations covering 1.2M patient interactions annually.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[25].id,
      companyId: indexedDocs[25].companyId,
      type: FactType.PRODUCT,
      subject: 'MarketingOS',
      predicate: 'product_features',
      object: 'Multi-channel attribution with 15+ marketing channel integrations',
      confidence: 0.93,
      sourceText: 'Product roadmap details multi-touch attribution across 15+ channels including Google, Meta, LinkedIn, and email.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[25].id,
      companyId: indexedDocs[25].companyId,
      type: FactType.OPPORTUNITY,
      subject: 'MarketingOS',
      predicate: 'market_expansion',
      object: 'Planning European expansion in 2026',
      confidence: 0.87,
      sourceText: 'Strategic roadmap includes European market entry targeted for Q1 2026 with UK and Germany as initial markets.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[26].id,
      companyId: indexedDocs[26].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'InsureTech Pro',
      predicate: 'loss_ratio',
      object: '62% combined loss ratio',
      confidence: 0.94,
      sourceText: 'Actuarial analysis confirms 62% combined loss ratio, indicating strong underwriting discipline.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[26].id,
      companyId: indexedDocs[26].companyId,
      type: FactType.FINANCIAL_METRIC,
      subject: 'InsureTech Pro',
      predicate: 'policies_written',
      object: '12,500 policies written in 2024',
      confidence: 0.96,
      sourceText: 'Platform underwrote and issued 12,500 insurance policies in 2024, representing 35% YoY growth.',
      extractedBy: 'claude-sonnet-4.5',
    },
    {
      documentId: indexedDocs[26].id,
      companyId: indexedDocs[26].companyId,
      type: FactType.PRODUCT,
      subject: 'InsureTech Pro',
      predicate: 'ai_capabilities',
      object: 'AI underwriting reduces processing time by 80%',
      confidence: 0.91,
      sourceText: 'AI-powered underwriting engine reduces policy processing time from 5 days to less than 24 hours (80% reduction).',
      extractedBy: 'claude-sonnet-4.5',
    },
  ];

  const createdFacts = [];

  for (const factData of factsData) {
    // Idempotent: Check if fact already exists
    const existing = await prisma.fact.findFirst({
      where: {
        documentId: factData.documentId,
        subject: factData.subject,
        predicate: factData.predicate,
      },
    });

    if (existing) {
      console.log(`  ↓ Fact "${factData.subject} - ${factData.predicate}" already exists (${existing.id})`);
      createdFacts.push(existing);
    } else {
      const fact = await prisma.fact.create({
        data: factData,
      });
      console.log(`  ✓ Created fact "${fact.subject} - ${fact.predicate}" (${fact.id})`);
      createdFacts.push(fact);
    }
  }

  return createdFacts;
}
